### ISSUE TITLE
landscape mode keyboard popup too big

### ISSUE THREAD

**Issue by UkeHa** [massijay/iOSMauiScrollUpOnKeyboardShow#1]
If you use your fix on an ipad in landscape mode you get either a big white area above the keyboard that blocks the entries (which can also not scroll away from) if your page is too long. Once your page is longer (?) than the keyboard + viewport the margin is bigger than reasonable. I also ran into this issue:

`An error occurred: 'Object reference not set to an instance of an object.'. Callstack: '   at W3AppMaui.Platforms.iOS.Utils.Extensions.GetViewRelativeBottom(UIView view, UIView rootView) in %myproject%\Platforms\iOS\Utils\Extensions.cs:line 44
   at %myproject%.Platforms.iOS.Utils.Extensions.GetOverlapDistance(UIView activeView, UIView rootView, CGRect keyboardFrame) in %myproject%\Platforms\iOS\Utils\Extensions.cs:line 64
   at %myproject%.Controls.FixedScrollView.OnKeyboardShowing(Object sender, UIKeyboardEventArgs args) in %myproject%\Controls\FixedScrollView.cs:line 26
   at UIKit.UIKeyboard.Notifications.<>c__DisplayClass10_0.<ObserveWillShow>b__0(NSNotification notification)
   at Foundation.InternalNSNotificationHandler.Post(NSNotification s)
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at W3AppMaui.Program.Main(String[] args) in %myproject%\Platforms\iOS\Program.cs:line 13
   at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)'`

**Comment by UkeHa** [comment]
Also, the margin should be added to the end of the page, so that you can scroll to the last entries, without overlaying them with the keyboard

**Comment by massijay** [comment]
I'm not developing with MAUI at the moment. I created this repo to showcase a workaround that worked for me before halting the project I was working on, I didn't test it on iPad though. Unfortunately I have no time right now to look into the issue

**Comment by UkeHa** [comment]
Here's a fix:

`			if (distance > 0  && DeviceDisplay.Current.MainDisplayInfo.Orientation == DisplayOrientation.Portrait)
			{
				Margin = new Thickness(Margin.Left, Margin.Top, Margin.Right, kbFrame.Height);
			}
			else if (distance > 0  && DeviceDisplay.Current.MainDisplayInfo.Orientation == DisplayOrientation.Landscape)
			{
				Margin = new Thickness(Margin.Left, Margin.Top, Margin.Right, kbFrame.Height);
			}`

**Comment by massijay** [comment]
It seems you put the same thing on both if and else blocks, so it can be semplified.

Keep also in mind that your code shifts up the page of keyboard height, independently of the keyboard hiding the entry or not, if this is what you want, then it's ok.

~~I can't remember why I set the margin top as minus the distance though 🤔~~ I did this because I didn't wanted the page to be shrinked but shift up

**Comment by UkeHa** [comment]
Hey, thanks for the reply. The main problem i ran into was that the shift up doesn't work once the page is too long. This point is reached even faster when used in landscape. If you shift up (even though the calculation of how far you should move the vieweport seems reasonable) at the end of the page, you shift out of the viewport and can't move up to the page again. Basically locking you from interacting with the page until you close the keyboard.
Shrinking it has the benefit of you still being able to interact with all elements, regardless of portrait or landscape
